environment:
  name: prod
  timeoutMs: 15000

  operators:
    sitea:
      domain: api.prod-site-a.com
      basePath: /x-api
      scheme: https
      parallelism: 8

    siteb:
      domain: api.prod-site-b.com
      basePath: /v2
      scheme: https
      parallelism: 4
